# Generated by Django 5.1.7 on 2025-03-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Izoh')),
                ('oquv_reja', models.CharField(max_length=100, verbose_name="O'quv reja")),
                ('oquv_yili', models.CharField(default='2024 (2024-2025)', max_length=20, verbose_name="O'quv yili")),
                ('semester', models.CharField(max_length=20, verbose_name='Semestr')),
                ('subject', models.CharField(max_length=255, verbose_name='Fanlar')),
                ('nazorat_turi', models.CharField(choices=[('Umumiy', 'Umumiy'), ('Yakuniy nazorat', 'Yakuniy nazorat')], max_length=50, verbose_name='Nazorat turi')),
                ('faol', models.BooleanField(choices=[(True, 'Ha'), (False, "Yo'q")], default=True, verbose_name='Faol')),
                ('boshlanish', models.DateTimeField(verbose_name='Boshlanish')),
                ('tugash', models.DateTimeField(verbose_name='Tugash')),
                ('vaqti_daqiqa', models.PositiveIntegerField(verbose_name='Vaqti (daqiqa)')),
                ('maks_ball', models.PositiveIntegerField(verbose_name='Maks. ball')),
                ('urinishlar', models.PositiveIntegerField(verbose_name='Urinishlar')),
                ('savollar_soni', models.PositiveIntegerField(verbose_name='Savollar soni')),
                ('tasodifiy', models.BooleanField(choices=[(True, 'Ha'), (False, "Yo'q")], default=False, verbose_name='Tasodifiy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imtihon',
                'verbose_name_plural': 'Imtihonlar',
            },
        ),
    ]
