# Generated by Django 5.1.7 on 2025-03-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='exams', to='backend.group', verbose_name='Guruhlar'),
        ),
    ]
