# Generated by Django 5.1.7 on 2025-03-19 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_exam_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=255, verbose_name='a) Variant')),
                ('option_b', models.CharField(max_length=255, verbose_name='b) Variant')),
                ('option_c', models.CharField(max_length=255, verbose_name='c) Variant')),
                ('option_d', models.CharField(max_length=255, verbose_name='d) Variant')),
                ('correct_option', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1, verbose_name="To'g'ri javob")),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='backend.exam')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
    ]
